baseURL = 'http://shuosc.github.io/'
title = 'SHUOSC Blog'
theme = 'FixIt'

# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true

[params]
  # FixIt 主题版本
  version = "0.2.X"
  # Header config
  [params.header]
    # FixIt 0.2.13 | CHANGED desktop header mode ("sticky", "normal", "auto")
    desktopMode = "sticky"
    # FixIt 0.2.13 | CHANGED mobile header mode ("sticky", "normal", "auto")
    mobileMode = "auto"
    # FixIt 0.2.0 | NEW Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/logo_title.webp"
      # title name
      name = "SHUOSC"

# 中文主页信息设置
[languages.zh-cn.params.home]
  # RSS 文章数目
  rss = 10
  # 主页个人信息
  [languages.zh-cn.params.home.profile]
    enable = true
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/logo.webp"
    # 主页显示的网站标题 (支持 HTML 格式)
    title = "上海大学开源社区"
    # 主页显示的网站副标题
    subtitle = "上海大学开源爱好者交流的平台"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # 免责声明 (支持 HTML 格式)
    disclaimer = ""
  # 主页文章列表
  [languages.zh-cn.params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6

# 中文菜单配置
[languages.zh-cn.menu]
  [[languages.zh-cn.menu.main]]
    identifier = "posts"
    # 父级菜单项的标识符 (identifier) since v0.2.14
    parent = ""
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = "<i class='fa-solid fa-archive fa-fw fa-sm'></i>"
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "所有文章"
    url = "/posts/"
    title = ""
    weight = 1
  [[languages.zh-cn.menu.main]]
    identifier = "categories"
    pre = "<i class='fa-solid fa-th fa-fw fa-sm'></i>"
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[languages.zh-cn.menu.main]]
    identifier = "tags"
    pre = "<i class='fa-solid fa-tags fa-fw fa-sm'></i>"
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[languages.zh-cn.menu.main]]
    identifier = "fly"
    pre = "<i class='fa-solid fa-book fa-fw fa-sm'></i>"
    name = "飞跃手册"
    url = "/fly/"
    title = ""
    weight = 4
  [[languages.zh-cn.menu.main]]
    identifier = "tests"
    pre = "<i class='fa-solid fa-flask fa-fw fa-sm'></i>"
    post = ""
    name = "测试"
    url = "/tests/"
    title = "FixIt 测试"
    weight = 5
    [languages.zh-cn.menu.main.params]
      draft = true
  [[languages.zh-cn.menu.main]]
    identifier = "friends"
    pre = "<i class='fa-solid fa-users fa-fw fa-sm'></i>"
    post = ""
    name = "友链"
    url = "/friends/"
    title = "友情链接"
    weight = 6
  [[languages.zh-cn.menu.main]]
    identifier = "about"
    pre = "<i class='fa-solid fa-info-circle fa-fw fa-sm'></i>"
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 7
  [[languages.zh-cn.menu.main]]
    identifier = "github"
    pre = "<i class='fa-brands fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/shuosc"
    title = "GitHub"
    weight = 8
    [languages.zh-cn.menu.main.params]
      class = "d-none-desktop text-center"

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/hugo-fixit/FixIt/issues/43)
    noClasses = false
